<?php
# This file was automatically generated by the MediaWiki 1.20alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

/************************************************************************
 * @section   MediaWiki core: Base settings
 *
 * @{
 */

## Database settings
$wgDBtype           = 'mysql';
$wgDBserver         = 'localhost';
$wgDBprefix         = '';
$wgDBTableOptions   = 'ENGINE=InnoDB, DEFAULT CHARSET=binary';

## General settings
$wgSitename = 'jQuery Wiki';
$wgMetaNamespace = 'Project';
$wgLanguageCode = 'en';
$wgDefaultSkin = 'jqdocs';

$wgScriptPath = '/mw';
$wgScriptExtension = '.php';

# To enable image uploads, make sure the 'images' directory is writable
$wgEnableUploads  = false;

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = false;

## We installed MediaWiki from Git
## Extensions are seperate clones in a higher directory, fix paths:
$ExtPath = dirname( realpath( $IP ) ) . '/mediawiki-extensions';
$wgExtensionAssetsPath = '/mw-extensions';


/**@}*/

/************************************************************************
 * @section   MediaWiki extensions
 *
 *
 * @{
 */

require_once( "$ExtPath/DynamicPageList/DynamicPageList.php" );

require_once( "$ExtPath/Interwiki/Interwiki.php" );

require_once( "$ExtPath/JqDocsSkin/JqDocsSkin.php" );

require_once( "$ExtPath/ParserFunctions/ParserFunctions.php" );


/**@}*/

/************************************************************************
 * @section   MediaWiki additional settings
 *
 *
 * @{
 */

## Settings specifically for stage and production

$isStage = false;

if ( WebRequest::detectServer() === 'http://stage.docs.jquery.com' ) {
	$isStage = true;
}

if ( $wgCommandLineMode ) {
	if ( defined( 'MW_DB' ) ) {
		if ( in_array( MW_DB, array( 'jqdocs_docs', 'jqdocs_stage' ) ) ) {
			$isStage = MW_DB === 'jqdocs_stage';
		} else {
			die( 'Unknown wiki: ' . MW_DB . "\n" );
		}
	} else {
		// Can't guess server from the CLI
		// --wiki jqdocs_stage or --wiki jqdocs_docs
		die( 'Command-line mode must specify which --wiki should be acted on. jqdocs_stage or jqdocs_docs.' . "\n" );
	}
}


if ( $isStage ) {

	// Stage settings:

	$wgDBname = 'jqdocs_stage';
	$wgServer = 'http://stage.docs.jquery.com';

	error_reporting( -1 );

	$wgShowExceptionDetails = true;

} else {

	// Production settings:

	$wgDBname = 'jqdocs_live';
	$wgServer = 'http://docs.jquery.com';

	error_reporting( 0 );
}


## Action paths, like "/edit/Page_name"
$actions = array(
	'view', 'edit', 'watch', 'unwatch', 'delete','revert', 'rollback',
	'protect', 'unprotect', 'markpatrolled', 'render', 'submit', 'history', 'purge'
);
foreach ( $actions as $action ) {
	$wgActionPaths[$action] = "/$action/$1";
}


## Override view, use "/Page_name" for regular page views.
$wgArticlePath = $wgActionPaths['view'] = "/$1";


## Subpages
# Enable in the main namespace
$wgNamespacesWithSubpages[NS_MAIN] = true;

## Global *.jquery.com favicon from static
$wgFavicon = 'http://static.jquery.com/favicon.ico';


## Allow raw HTML inside wiki markup through <html> tags
## Disabled by default, but enabled for jqdocs for backwards compatibility.
$wgRawHtml = true;
$wgWellFormedXml = false;


## Caching and optimization

$wgUseGzip = true;

$wgEnableParserCache = true;

# Don't show "anonymous user <IP here>" in headings,
# this wiki is mostly for reading. Also keeps it cacheable.
$wgShowIPinHeader = false;

# Shared memory settings
# CACHE_DB: object_cache table in db
# CACHE_ACCEL: faster, but needs php-apc installed
$wgMainCacheType = CACHE_ACCEL;

# File cache at "/var/www/<domain>/mw-cache", sibling of public_html
$wgUseFileCache = true;
$wgCacheDirectory = dirname( $IP ) . '/mw-cache';

$wgDisableAnonTalk = true;

## Set user permissions:

# Rename legacy group 'sysop' to 'wiki-admin'
$wgGroupPermissions['wiki-admin'] = $wgGroupPermissions['sysop'];

# Merge sysop, checkuser, developer and bureaucrat into wiki-admin
unset( $wgGroupPermissions['sysop'] );
unset( $wgGroupPermissions['checkuser'] );
unset( $wgGroupPermissions['developer'] );
unset( $wgGroupPermissions['bureaucrat'] );

$wgGroupPermissions['wiki-admin']['userrights']  = true;
$wgGroupPermissions['wiki-admin']['editinterface']  = true;

# Account creation: Disable for readers, users; Enable for wiki-admins
$wgGroupPermissions['*']['createaccount'] =
$wgGroupPermissions['user']['createaccount'] = false;

$wgGroupPermissions['wiki-admin']['createaccount'] = true;

# Editing: Disable for readers; Enable for users
$wgGroupPermissions['*']['edit'] =
$wgGroupPermissions['*']['writeapi'] =
$wgGroupPermissions['*']['createpage'] =
$wgGroupPermissions['*']['createtalk'] =
$wgGroupPermissions['*']['minoredit'] = false;

$wgGroupPermissions['user']['edit'] =
$wgGroupPermissions['user']['writeapi'] =
$wgGroupPermissions['user']['createtalk'] =
$wgGroupPermissions['user']['createpage'] =
$wgGroupPermissions['user']['minoredit'] = true;

# Uploads: Disable for users; Enable for wiki-admins
$wgGroupPermissions['user']['upload'] =
$wgGroupPermissions['user']['reupload'] =
$wgGroupPermissions['user']['reupload-shared'] = false;

$wgGroupPermissions['wiki-admin']['upload'] =
$wgGroupPermissions['wiki-admin']['reupload'] =
$wgGroupPermissions['wiki-admin']['reupload-shared'] = true;

# Enable delete-revision feature
$wgGroupPermissions['wiki-admin']['deleterevision']  = true;

# Extension:Interwiki
$wgGroupPermissions['wiki-admin']['interwiki']  = true;


## Hide old user preferences

# personal
$wgHiddenPrefs[] = 'skin';
$wgHiddenPrefs[] = 'realname';
$wgHiddenPrefs[] = 'nickname';
$wgHiddenPrefs[] = 'fancysig';
# rendering
$wgHiddenPrefs[] = 'imagesize';
$wgHiddenPrefs[] = 'underline';
$wgHiddenPrefs[] = 'highlightbroken';
$wgHiddenPrefs[] = 'showjumplinks';
$wgHiddenPrefs[] = 'numberheadings';
$wgHiddenPrefs[] = 'vector-noexperiments';
# editing
$wgHiddenPrefs[] = 'previewontop';
$wgHiddenPrefs[] = 'editsection';
$wgHiddenPrefs[] = 'editsectiononrightclick';
$wgHiddenPrefs[] = 'editondblclick';
$wgHiddenPrefs[] = 'showtoolbar';
$wgHiddenPrefs[] = 'minordefault';
$wgHiddenPrefs[] = 'externaleditor';
$wgHiddenPrefs[] = 'externaldiff';
# rc
$wgHiddenPrefs[] = 'usenewrc';
# searchoptions
$wgHiddenPrefs[] = 'vector-simplesearch';
# misc
$wgHiddenPrefs[] = 'diffonly';
$wgHiddenPrefs[] = 'norollbackdiff';


## Set default user preferences

# personal
$wgDefaultUserOptions['ccmeonemails'] = 1;
# searchoptions
$wgDefaultUserOptions['searchlimit'] = 25;
# watchlist
$wgDefaultUserOptions['watchlistdays'] = 0;


/************************************************************************
 * @section   Include other files (must be last)
 *
 * @{
 */

require_once( __DIR__ . '/PrivateSettings.php' );


/**@}*/
